include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

stages:
  - test
  - deploy

variables:
  BUNDLE: 'gnome-games-git.flatpak'

tests:
  image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master
  stage: test
  tags:
    - flatpak
  variables:
    MANIFEST_PATH: 'flatpak/org.gnome.Games.UnitTests.yml'
  script:
    - flatpak-builder --user --disable-rofiles-fuse unit-tests ${MANIFEST_PATH}
    - xvfb-run -a -s '-screen 0 1024x768x24' flatpak-builder --disable-rofiles-fuse --run unit-tests ${MANIFEST_PATH} games-unit-tests
  cache:
    paths:
      - .flatpak-builder/downloads
      - .flatpak-builder/git

flatpak:
  extends: '.flatpak'
  variables:
    MANIFEST_PATH: 'flatpak/org.gnome.Games.json'
    RUNTIME_REPO: 'https://nightly.gnome.org/gnome-nightly.flatpakrepo'
    FLATPAK_MODULE: 'gnome-games'
    APP_ID: 'org.gnome.GamesDevel'
    GIT_SUBMODULE_STRATEGY: recursive

review:
  dependencies:
    - 'flatpak'
  extends: '.review'

stop_review:
  extends: '.stop_review'

nightly:
  extends: '.publish_nightly'
