
.build_template: &distro_build
  script:
    - meson -Dmanpage=false _build
    - ninja -C _build install

stages:
  - build-flatpak

flatpak:unit-tests:
  image: registry.gitlab.gnome.org/gnome/gnome-nightly-oci/nightly:master
  stage: build-flatpak
  variables:
    MANIFEST_PATH: "flatpak/org.gnome.Games.UnitTests.json"
  script:
    - flatpak-builder unit-tests ${MANIFEST_PATH}
    - xvfb-run -a -s "-screen 0 1024x768x24" flatpak-builder --run unit-tests ${MANIFEST_PATH} games-unit-tests
  cache:
    paths:
      - .flatpak-builder/cache/
      - .flatpak-builder/downloads/
      - .flatpak-builder/git/

flatpak:gnome-games:
  image: registry.gitlab.gnome.org/gnome/gnome-nightly-oci/nightly:master
  stage: build-flatpak
  variables:
    MANIFEST_PATH: "flatpak/org.gnome.Games.json"
    RUNTIME_REPO: "https://sdk.gnome.org/gnome-nightly.flatpakrepo"
    FLATPAK_MODULE: "gnome-games"
    BUNDLE: "gnome-games-git.flatpak"
  script:
    - flatpak-builder --stop-at=${FLATPAK_MODULE} app ${MANIFEST_PATH}
    - flatpak build app ./autogen.sh --prefix=/app
    - flatpak build app make
    - flatpak build app make install
    - flatpak build app mkdir -p /app/lib/libretro/extra.d
    - flatpak-builder --finish-only --repo=repo app ${MANIFEST_PATH}
    - flatpak build-bundle repo ${BUNDLE} --runtime-repo=${RUNTIME_REPO} org.gnome.Games
  artifacts:
    paths:
      - ${BUNDLE}
    expire_in: 2 days
  cache:
    paths:
      - .flatpak-builder/cache/
      - .flatpak-builder/downloads/
      - .flatpak-builder/git/
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://gitlab.gnome.org/$CI_PROJECT_PATH/-/jobs/$CI_JOB_ID/artifacts/raw/${BUNDLE}
