include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

stages:
  - test
  - deploy

variables:
  BUNDLE: 'gnome-games-git.flatpak'

tests:
  image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master
  stage: test
  variables:
    MANIFEST_PATH: 'flatpak/org.gnome.Games.UnitTests.yml'
  script:
    - flatpak-builder unit-tests ${MANIFEST_PATH}
    - xvfb-run -a -s '-screen 0 1024x768x24' flatpak-builder --run unit-tests ${MANIFEST_PATH} games-unit-tests
  cache:
    paths:
      - .flatpak-builder/downloads
      - .flatpak-builder/git

flatpak:
  extends: '.flatpak'
  variables:
    MANIFEST_PATH: 'flatpak/org.gnome.Games.json'
    RUNTIME_REPO: 'https://nightly.gnome.org/gnome-nightly.flatpakrepo'
    FLATPAK_MODULE: 'gnome-games'
    APP_ID: 'org.gnome.GamesDevel'
    MESON_ARGS: '-Dprofile=development'

review:
  dependencies:
    - 'flatpak'
  extends: '.review'

stop_review:
  extends: '.stop_review'

nightly:
  extends: '.publish_nightly'

lint:
  image: valalang/lint:latest
  stage: .pre
  script:
    - io.elementary.vala-lint -c build-aux/vala-lint.conf src plugins
